### PR TITLE
#298: Improved usage of player custom color

### PR DESCRIPTION
**Pull request by Ellypse**
- Removed individual settings for color contrast, consolidated into one setting on the General settings
- Added `:GetCustomColorForDisplay()` to the Player model, to get color that follows the global setting for increased color contrast. `:GetCustomColoredRoleplayingNamePrefixedWithIcon()` uses this one instead of the raw `:GetCustomColor()` now
- Added more ways to creates a `Player` to accomodate chat frames, such as `Player.static.CreateFromGUID(guid)` or `Player.static.CreateFromNameAndRealm(name[, realm])`
- Added PUBLIC `AddOn_TotalRP3.Configuration.shouldDisplayIncreasedColorContrast()` for third parties

### CODE REVIEW

**Comment by Meorawr** [comment]
> Removed individual settings for color contrast, consolidated into one setting on the General settings

Should there be migration stuff added to make it so that if you had *any* of the individual settings checked, the (new?) setting should be enabled?

**Comment by Ellypse** [comment]
> > Removed individual settings for color contrast, consolidated into one setting on the General settings
> 
> Should there be migration stuff added to make it so that if you had _any_ of the individual settings checked, the (new?) setting should be enabled?

That is a valid thing that I thought about briefly before forgetting. It seems trivial to check if one of them was enabled and switch the new setting on in that case. Good call.

**Comment by Meorawr** [comment]
> Added PUBLIC AddOn_TotalRP3.Configuration.shouldDisplayIncreasedColorContrast() for third parties

I'm a bit on the fence about this change; if we add functions for *every* setting as part of the public API, suddenly removing a setting later on (like we're doing here!) either means you're left with deprecated functions that do nothing, or cleaning them up becomes an API breakage.

I think exposing config keys and just having a pair of `IsValidConfigKey(key)` and `GetConfigValue(key)` type functions is best for public use.

**Comment by Ellypse** [comment]
> I'm a bit on the fence about this change; if we add functions for _every_ setting as part of the public API, suddenly removing a setting later on (like we're doing here!) either means you're left with deprecated functions that do nothing, or cleaning them up becomes an API breakage.
> 
> I think exposing config keys and just having a pair of `IsValidConfigKey(key)` and `GetConfigValue(key)` type functions (with better names) is best for **public** use.

That is indeed the future I want, but that felt out of scope for now, so I went with a quick and easy way 🤷‍♂

**Comment by Meorawr** [comment]
If it's the future you want, perhaps document the function as for internal use only for now, at least until we sort out the config API?

**Pull request merged**
