### PR TITLE
Clear All Points on target_frame anchor update

### PR DESCRIPTION
**Pull request by Solanya**
nice joke of a system, blizz

### CODE REVIEW

**Comment by Ellypse** [comment]
Why was this merged without the requested change done?

**Comment by Meorawr** [comment]
Because as noted the context that function is called in only occurs once on initialization.

**Comment by Ellypse** [comment]
Oh okay. I didn't see that here. Move along then.

**Comment by Meorawr** [comment]
image

Context for future reference :)

**Pull request merged**
