### PR TITLE
You sit on a throne of lies - only left-click works

### PR DESCRIPTION
**Pull request by Raenore**
image

will-ferrell-elf

### CODE REVIEW

**Comment by Solanya** [comment]
Ok but if you're gonna change that one, at least change the one in the companion list too

**Comment by Raenore** [comment]
> Ok but if you're gonna change that one, at least change the one in the companion list too

No.


...Okay.

**Comment by Raenore** [comment]
Will this tyranny never end of me being forced upon with more work..

image

**Review by Solanya — APPROVED** [review]
Never

**Pull request merged**
