### PR TITLE
Fix Classic compatibility

### PR DESCRIPTION
**Pull request by Meorawr**
yay classic

### CODE REVIEW

**Review by Solanya — APPROVED** [review]
yay

**Review by Raenore — APPROVED** [review]
Oh yeah, I knew I was forgetting something when I CTRL+F'd `Ellyb.Icon`.

Thank you Meorawr, the first of his name.. Protector of the seven RP realms and.. Wait, in a GoT world.. Who would sit on the Iron Throne? Sol or Meorawr? I wonder..

**Comment by Meorawr** [comment]
me

**Comment by Solanya** [comment]
better watch the wine you drink

**Pull request merged**
